<?php
/**
 * @var array $comment
 */
?>
<h2>Delete Confirmation</h2>
<form method="post">
    <p>Are you sure you want to delete this comment?</p>
    <div class="card p-3 mb-2">
        <div class="d-flex justify-content-between align-items-center">
            <div class="user d-flex flex-row align-items-center">
                <span>
                    <small class="font-weight-bold text-primary"><?= $comment['author'] ;?></small>
                </span>
            </div>
            <small><?= $comment['published'] ;?></small>
        </div>
        <p class="mt-2"><?= $comment['description'] ;?></p>
    </div>

    <input type="hidden" name="confirm" value="1">
    <input type="hidden" name="id" value="<?= $comment['id'] ?>">
    <input type="hidden" name="post_id" value="<?= $comment['post_id'] ?>">
    <button type="submit" class="btn btn-danger">Yes, Delete it</button>
    <a class="btn btn-secondary" href="index.php?page=post&action=view&id=<?= $comment['post_id'] ?>">Cancel</a>
</form>