<?php
/**
 * @var array $to_delete
 */
?>
<h2>Delete Confirmation</h2>
<form method="post">
    <p>Are you sure you want to delete this post?</p>
    <input type="hidden" name="confirm" value="1">
    <input type="hidden" name="id" value="<?= $to_delete['id'] ?>">
    <button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i> Yes, Delete it</button>
    <a class="btn btn-secondary" href="index.php?page=post&action=my_posts">Cancel</a>
</form>