<?php
/**
 * @var array $posts
 */
?>

<h2>My Posts</h2>
<?php if (count($posts) == 0): ?>
    <div class="alert alert-warning alert-icon">
        <span>There are no posts</span>
    </div>
<?php endif; ?>
<?php foreach ($posts as $post): ?>
    <div class="card p-3 mb-2">
        <div class="row">
            <div class="col-md-3">
                <a href="index.php?page=post&action=view&id=<?= $post['id']; ?>">
                    <img src="image.php?img=<?= $post['image'] ?>" class="rounded w-100 img-fluid">
                </a>
            </div>
            <div class="col-md-9">
                <div style="position: absolute; right: 0">
                    <form method="post" action="index.php?page=post&action=delete" class="mr-2">
                        <button type="submit" class="btn btn-danger ms-2 delete-post-btn"><i class="fa fa-trash-o"></i></button>
                        <input type="hidden" name="id" value="<?= $post['id']; ?>">
                    </form>
                    <a class="btn btn-warning mt-1" href="index.php?page=post&action=edit&id=<?= $post['id'] ?>"><i class="fa fa-pencil"></i></a>
                </div>
                <div>
                    <h5>
                        <a href="index.php?page=post&action=view&id=<?= $post['id']; ?>"><?= $post['title']; ?></a>
                    </h5>
                    <div class="mb-1"><i class="fa fa-eye"></i> <span class="ms-1 views"><?= $post['visits'] ?></span></div>
                    <div class="mb-1">
                        Author: <strong><?= $post['author']; ?></strong>
                    </div>
                    <span class="days-ago"><?= $post['created_at']; ?></span>
                </div>
            </div>
        </div>
    </div>
<?php endforeach; ?>