<?php
/*require_once '../../src/register/controller/Input.php';

if(Input::exists()) {
    $validate = new Validate();
    $validation = $validate->check($_POST,array(
        'username'=>array(
            'required' => true,
            'min' => 2,
            'max' => 20,
            'uniqe'=>'users'
        ),
        'password' => array(
            'required'=> true,
            'min'=> 6,
        ),
        'passwordRepeat' => array(
            'required'=> true,
            'matches'=> 'password'
        )
    ));
    if($validation->passed()){
        //register user
    }else{
        //output errors
    }
}
*/?>

<form class="form-signin" method="post" action="index.php?page=home&action=register">
    <h1 class="h3 mb-3 font-weight-normal">Register</h1>
    <label for="inputEmail" class="sr-only">Email address</label>
    <input type="text" id="inputEmail" class="form-control" name="username"
           placeholder="Email address" required autofocus>
    <label for="inputPassword" class="sr-only">Password</label>
    <input type="password" id="inputPassword" class="form-control" name="password"
           placeholder="Password" required>
    <label for="inputPasswordRepeat" class="sr-only">Password Repeat</label>
    <input type="password" id="inputPasswordRepeat" class="form-control" name="password_repeat"
           placeholder="Password Repeat" required>
    <label>
        <select id="type" name="account_type" class="form-control">
            <option value="admin">Admin</option>
            <option value="guest">Guest</option>
        </select>
    </label>
    <?php if (!empty($error)): ?>
    <div class="alert alert-danger">
        <?= $error ?>
    </div>
    <?php endif; ?>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Register</button>
    <p class="mt-5 mb-3 text-muted">&copy; 2017-2020</p>
</form>