<?php
/**
 * @var array $posts
 * @var array $top_post
 */
?>
<!-- Top Post-->
<div class="row gx-4 gx-lg-5 align-items-center my-5">
    <div class="col-lg-7"><img class="img-fluid rounded mb-4 mb-lg-0" src="image.php?img=<?= $top_post['image'] ?>"></div>
    <div class="col-lg-5">
        <h1 class="font-weight-light"><?= $top_post['title'] ?></h1>
        <p><?= substr($top_post['description'], 0, 250) ?>...</p>
        <a class="btn btn-primary" href="index.php?page=blog&action=view&id=<?= $top_post['id'] ?>">View Post</a>
    </div>
</div>
<!-- Post List-->
<div class="row gx-3 gx-lg-3" >
    <?php foreach ($posts as $post): ?>
    <div class="col-md-4 mb-5">
        <div class="card h-100">
            <div class="card-body">
                <img class="img-fluid rounded mb-4 mb-lg-0" src="image.php?img=<?= $post['image'] ?>" alt="<?= $post['title'] ?>" />
                <h4 class="card-title"><?= $post['title'] ?></h4>
                <p class="card-text"><?= substr($post['description'], 0, 200) ?>...</p>
            </div>
            <div class="card-footer">
                <a class="btn btn-primary btn-sm" href="index.php?page=blog&action=view&id=<?= $post['id'] ?>">More Info</a>
            </div>
        </div>
    </div>
    <?php endforeach; ?>
</div>
